fix error C2440: 'static_cast': cannot convert from 'T' to 'Json::String' with [    T=const char8_t * ] 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string': no overloaded function could convert all the argument types [...huge blurb from compiler about what /could be/ ...] see reference to function template instantiation 'JsonTest::TestResult &JsonTest::checkEqual<const char8_t*,Json::String>(JsonTest::TestResult &,T,U,const char *,unsigned int,const char *)' being compiled with [     T=const char8_t *,     U=Json::String ]